networks:
  shared-net:
    name: multi-team-dev-deployment_shared-net
    external: true

services:
  backend:
    image: bmdarklight/nexa-api:latest
    container_name: nexa-backend
    env_file:
      - .env
    command: sh -c "uvicorn api.main:app --host 0.0.0.0 --port ${API_PORT:-8000}"
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    networks:
      - shared-net

  frontend:
    image: bmdarklight/nexa-ui:latest
    container_name: nexa-frontend
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_SERVER_URL=${NEXT_PUBLIC_SERVER_URL}
      - NEXT_PUBLIC_API_PORT=${NEXT_PUBLIC_API_PORT}
      - NEXT_PUBLIC_UI_PORT=${NEXT_PUBLIC_UI_PORT}
      - UI_PORT=${UI_PORT:-8010}
    ports:
      - "${UI_PORT:-8010}:${UI_PORT:-8010}"
    networks:
      - shared-net
    depends_on:
      - backend
